---

## Assignment Instructions

- Buatlah Tensor dibawah ini dengan Python:

  $$
  \begin{bmatrix}   \begin{bmatrix}   23 & 50 \\   7 & 12 \\   \end{bmatrix}   \begin{bmatrix}   57 & 67 \\   99 & 43   \end{bmatrix} \\    \begin{bmatrix}   75 & 21 \\   57 & 12 \\   \end{bmatrix}   \begin{bmatrix}   87 & 26 \\   18 & 84   \end{bmatrix}   \end{bmatrix}
  $$

- Lakukan perkalian terhadap matrix berikut:

  $$
  A =
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  \begin{bmatrix}
  17 \\
  22 \\
  19
  \end{bmatrix}
  $$

- Lakukan Transpose, hitung determinan, dan inverse terhadap matrix dibawah ini:

  $$
  \begin{bmatrix}
  23 & 50 & 19 \\
  7 & 12 & 109 \\
  57 & 67 & 98
  \end{bmatrix}
  $$



## Answer

### Memasukan library yang digunakan

In [1]:
import numpy as np

### Soal 1

In [5]:
tensor = np.array([
                    [[23,50],[7,12]],
                    [[57,67],[99,67]],
                    [[75,21],[57,12]],
                    [[87,26],[18,84]]
                    ]) # Membuat tensor
tensor

array([[[23, 50],
        [ 7, 12]],

       [[57, 67],
        [99, 67]],

       [[75, 21],
        [57, 12]],

       [[87, 26],
        [18, 84]]])

### Soal 2

In [15]:
matrix = np.array([
                    [23,50,19],
                    [7,12,109],
                    [57,67,98]
                  ]) # Membuat matrix 3x3
perkalian = np.array([17,22,19]) # membuat matrix 1x3 untuk pengalian

In [16]:
matrix @ perkalian # Mengalikan variabel matrix dengan variabel perkalian lalu hasilnya dijumlahkan

array([1852, 2454, 4305])

### Soal 3

In [17]:
matrix = np.array([
                    [23,50,19],
                    [7,12,109],
                    [57,67,98]
                  ]) # Membuat matrix 3x3

In [36]:
print (f"Hasil Transpose:\n {matrix.T}") # Menampilkan Transpose dari matrix (kolom jadi baris dan baris jadi kolom)
print('')
print (f"Hasil Determinan:\n {np.linalg.det(matrix)}") # Menampilkan Determinan dari matrix
print('')
print (f"Hasil Inverse:\n {np.linalg.inv(matrix)} ") # Menampilkan Inverse dari matrix

Hasil Transpose:
 [[ 23   7  57]
 [ 50  12  67]
 [ 19 109  98]]

Hasil Determinan:
 131344.0000000002

Hasil Inverse:
 [[-0.0466485  -0.02761451  0.03975819]
 [ 0.04208034  0.00891552 -0.01807467]
 [-0.00163692  0.0099662  -0.00056341]] 
